### PR TITLE
Add window event

### PR DESCRIPTION
**Pull request by KhantParthkumarA**
### Why needed these changes?
- Model should be reset on window click

### Have you tested these changes?
- Yes

### Any updates require?
- No

### CODE REVIEW

**Comment by kevinmmansour** [comment]
What about the save modal?

Save modal

Settings, about and save modal. Did I miss something?

**Comment by KhantParthkumarA** [comment]
> What about the save modal?
> 
> Save modal
> 
> Settings, about and save modal. Did I miss something?

Yes we've to add model reset for save also, I'll update it

**Comment by kevinmmansour** [comment]
Don't we do the same thing here:

```javascript
const AboutOnClick = ({
    target
}) => {
    if (target === About) {
        OpenCloseAbout();
    }
};
```

**Comment by KhantParthkumarA** [comment]
> Don't we do the same thing here:
> 
> ```js
> const AboutOnClick = ({
>     target
> }) => {
>     if (target === About) {
>         OpenCloseAbout();
>     }
> };
> ```

Window events how we can handle in this function call?

**Comment by KhantParthkumarA** [comment]
@kevinmmansour  Let me know if anything need to update

**Pull request closed without merging**
