### PR TITLE
Sample markdown button

### PR DESCRIPTION
**Pull request by KhantParthkumarA**
### Why needed these changes?
- Get a sample of markdown

### Have you tested these changes?
- Yes

### Any updates require?
- No

### CODE REVIEW

**Comment by KhantParthkumarA** [comment]
I was added `Sample` button style in the last commit, but it not showing a live preview, please verify

**Comment by KhantParthkumarA** [comment]
I've used a sample reference from here - https://markdown-it.github.io/
Let me know if need to update urls and links etc

**Comment by lee-jongwoo** [comment]
I see there are explanations about features we don't support yet.
Delete the following:
- Advertisement
- Typographic replacement
- Right-Aligned table columns
- Subscript, Superscript
- Inserted, Marked Text
- Footnotes
- Abbreviations
- Custom Containers

Plus, all the links there are connected to _markdown-it_ wikis.
We'll need to change them, too.

**Comment by KhantParthkumarA** [comment]
> I see there are explanations about features we don't support yet. Delete the following:
> 
> * Advertisement
> * Typographic replacement
> * Right-Aligned table columns
> * Subscript, Superscript
> * Inserted, Marked Text
> * Footnotes
> * Abbreviations
> * Custom Containers
> 
> Plus, all the links there are connected to _markdown-it_ wikis. We'll need to change them, too.

Okay

**Comment by kevinmmansour** [comment]
There's a lot of problems here, I think we should redesign the header because it's started to be long, this's how it looks like on my device:

image

The scrollbar started to be annoying, let me just redesign and I'll be back to this pull request as well as a notice for @KhantParthkumarA, that the "Sample" button looks black - I haven't reviewed the code, so I don't know where's the problem and we don't allow advertisement -  sorry, even I as a maintainer I work a lot for this project and it's open source - the project aims and developed to be a good markdown text editor and help people to write READMEs and text files for their projects simply. As well as I would thank @lee-jongwoo for their time.

**Comment by KhantParthkumarA** [comment]
> I haven't reviewed the code, so I don't know where's the problem and we don't allow advertisement - sorry, even I as a maintainer I work a lot for this project and it's open source - the project aims and developed to be a good markdown text editor and help people to write READMEs and text files for their projects simply. As well as I would thank @lee-jongwoo for their time.

I'll remove advertisements and other links related changes that mention by @lee-jongwoo.
About the black color, I've already update styles in the last commit and doubly checked locally, It's seen fine locally, I think the last changes aren't showing on live preview as I was mentioned

**Comment by lee-jongwoo** [comment]
@kevinmmansour I'm actually thinking about using font-awesome icons. They have all the icons we need (displaying 'link' as 'a' is probably not a good idea) and icons cover less space than text.
I actually tried that:
스크린샷 2021-10-03 오전 7 59 19
It looked awesome.
(just got up, 7AM in the morning now)

**Comment by kevinmmansour** [comment]
> 
> 
> @kevinmmansour I'm actually thinking about using font-awesome icons. They have all the icons we need (displaying 'link' as 'a' is probably not a good idea) and icons cover less space than text. I actually tried that: 스크린샷 2021-10-03 오전 7 59 19 It looked awesome. (just got up, 7AM in the morning now)

Oh, nice work! I'm also thing about adding more markdown stuff like "H4", "H5", "H6" and etc but the problem that there's no space for that.

**Comment by kevinmmansour** [comment]
@lee-jongwoo In order to don't add much comments for this pull request, I have created [a new GitHub discussion](https://github.com/msk-apps/msk-markdown/discussions/24), so we can be clear and clean - thanks!

@KhantParthkumarA I'll be back to this pull request when I finish and push redesigning the header - because the header started to be messy.

**Comment by KhantParthkumarA** [comment]
> > 
> > 
> > @kevinmmansour I'm actually thinking about using font-awesome icons. They have all the icons we need (displaying 'link' as 'a' is probably not a good idea) and icons cover less space than text. I actually tried that: 스크린샷 2021-10-03 오전 7 59 19 It looked awesome. (just got up, 7AM in the morning now)
> 
> Oh, nice work! I'm also thinking about adding more markdown stuff like "H4", "H5", "H6" and etc. But the problem that there's no space for that.

We can do like drop-down menus for equals features like h1, h2... we can use drop down

**Pull request closed without merging**
