### PR TITLE
Scrollbar style changes

### PR DESCRIPTION
**Pull request by vaishak10**
**Purpose of Pull request**
    Increase the scrollbar width and border-radius so that scrolling up/down on both sections is done in a convenient way and providing a better look to the scrollbar.

**Does it affect the functionality of the application**
   No. It's just a styling change for the scrollbar on both sections of the application.

### CODE REVIEW

**Comment by lee-jongwoo** [comment]
I found that scrolling long markdown files on iOS devices are somewhat hard. You can see the scrolling is not smooth, and it's hard to scroll much content at once.
It's because [momentum scrolling](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/) is disabled by default in other scrolling areas.
```
-webkit-overfow-scrolling: touch
```
Add this, and the scrolling will be easier.

**Comment by vaishak10** [comment]
@lee-jongwoo, have enabled momentum scrolling by adding the snippet. But is it just for ios? I am facing the same in windows.

**Comment by lee-jongwoo** [comment]
This Momentum scrolling value is for iOS devices (like many other -webkit prefixes).
I think there is a chrome flag to enable this on touchpads, but it won’t work by default.
I haven’t heard anything about momentum scrolling on Windows touchscreens; can’t test one myself

**Review by lee-jongwoo — CHANGES_REQUESTED** [review]
The `-webkit-overflow-scrolling` value should be set on the scrolling container (the editor and viewer area), not the scrollbar pseudo-element itself.

**Comment by kevinmmansour** [comment]
[-webkit-overflow-scrolling](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling), there is an example there, I think it should work everywhere not just on iOS, no?

**Comment by vaishak10** [comment]
@lee-jongwoo have set the `-webkit-overflow-scrolling` for both viewer and editor containers. Any feedback?

**Comment by lee-jongwoo** [comment]
@vaishak10  The `#editor` element is a <div> wrapping the textarea, not the textarea itself.
Seems like `#getm` will be the correct one.
@kevinmmansour The MDN support table shows no browser is supporting this, but I tested myself; it only works on iOS Safari. On Android momentum scrolling is enabled for scrolling containers, but in iOS this is disabled.

**Comment by kevinmmansour** [comment]
Good idea - As well as redesigning the scrollbar, I think we also need to change colors for scrollbars as well as some stuff for Firefox since Firefox doesn't support WebKit.

Firstly, need to update CSS Variables. I suggest as below:

```css
:root{
    --font-color:#090821;
    --bg-color:#FFFFFF;
    --afont-color:#fc2f70;
    --dbgh-color: #e22a64;
    --dbga-color: #e22a64;
}
[data-theme="dark"]{
    --font-color:#f8f8f2;
    --bg-color:#111;
    --afont-color:#3cefff;
    --dbgh-color: #36d7e5;
    --dbga-color: #36d7e5;
}
```
Then update WebKit stuff like below:

```css
body::-webkit-scrollbar {
    width: 8px;
    height: 8px;
    -webkit-overflow-scrolling: touch;
}

body::-webkit-scrollbar-thumb {
    background-color: var(--afont-color);
    border-radius: 10px;
}

body::-webkit-scrollbar-thumb:hover {
    background: var(--dbgh-color);
}
body::-webkit-scrollbar-thumb:active {
    background: var(--dbga-color);
}
```

Then update this for Firefox:

```css
* {
    box-sizing: border-box;
    outline: 0;
    border: 0;
    scrollbar-width: thin;
    scrollbar-color: var(--afont-color) var(--bg-color);
}
```

As well as momentum scrolling as @lee-jongwoo mentioned (thanks!).

**Comment by vaishak10** [comment]
@lee-jongwoo has set the change directly for textarea. Please check

**Review by lee-jongwoo — APPROVED** [review]
Yes, ready for merge.

**Comment by vaishak10** [comment]
@kevinmmansour All the commits are finalized for this PR and it's ready for merge.

**Pull request merged**
